# Generated by Django 4.2.2 on 2023-07-15 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.TextField()),
                ('applicantid', models.TextField()),
                ('salary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.TextField()),
                ('employerid', models.TextField()),
                ('salary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.TextField()),
                ('employerid', models.TextField()),
                ('applicantid', models.TextField()),
                ('boolean', models.BooleanField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
