# Generated by Django 4.2.3 on 2023-07-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='salary',
            new_name='encrypted_desired_salary',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='salary',
            new_name='encrypted_expected_salary',
        ),
        migrations.AddField(
            model_name='applicant',
            name='public_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='public_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
