# Generated by Django 4.2.3 on 2023-07-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_encrypted_desired_salary_applicant_applicant_cipher_salary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='applicant_cipher_salary',
            new_name='cipher_salary',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='applicantid',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employer_cipher_salary',
            new_name='cipher_salary',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='employerid',
            new_name='userid',
        ),
    ]
